
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  tls:
  - hosts:
    - "sistema.korok.app"
    secretName: sistema-korok-tls-certificate
  - hosts:
    - "korok.app"
    secretName: korok-tls-certificate
  - hosts:
    - "jenkins.korok.app"
    secretName: jenkins-korok-tls-certificate
  - hosts:
    - "fiscal.korok.app"
    secretName: fiscal-korok-tls-certificate
  - hosts:
    - "jira.korok.app"
    secretName: jira-korok-tls-certificate
  - hosts:
    - "www.korok.app"
    secretName: www-korok-tls-certificate
  - hosts:
    - "api.korok.app"
    secretName: apigateway-tls-certificate
  rules:
  - host: api.korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-apigateway-service
          servicePort: 8080
  - host: sistema.korok.app
    http:
      paths:
      - path: /login
        backend:
          serviceName: {{ .Release.Name }}-autenticador-service
          servicePort: 3030
      - path: /ReportServer
        backend:
          serviceName: ssrs-service
          servicePort: 80
      - path: /Reports
        backend:
          serviceName: ssrs-service
          servicePort: 80
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-mainreact-service
          servicePort: 5000
  - host: korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-korok-service
          servicePort: 80
  - host: www.korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-korok-service
          servicePort: 80
  - host: jenkins.korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-jenkins-service
          servicePort: 8080
  - host: fiscal.korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-fiscal-service
          servicePort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-auth
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Korok'
spec:
  tls:
  - hosts:
    - "utils.korok.app"
    secretName: utils-korok-api-tls-certificate
  rules:
  - host: utils.korok.app
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-korok-utils-api-service
          servicePort: 80
