apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  protocol: {{ .Values.protocol | b64enc }}
  dbusername: {{ .Values.dbusername | b64enc }}
  dbpassword: {{ .Values.dbpassword | b64enc }}
  dbprod: {{ .Values.dbprod | b64enc }}
  dbdev: {{ .Values.dbdev | b64enc }}
  dbhost: {{ .Values.dbhost | b64enc }}
  dbcommon: {{ .Values.dbcommon | b64enc }}
  parserkey: {{ .Values.parserkey | b64enc }}
  resettoken: {{ .Values.resettoken | b64enc }}
  sresettoken: {{ .Values.sresettoken | b64enc }}
  azureacc: {{ .Values.azureacc | b64enc }}
  azurekey: {{ .Values.azurekey | b64enc }}
  serverurl: {{ .Values.serverurl | b64enc }}
  firebaseurl: {{ .Values.firebaseurl | b64enc }}
  cookiesecret: {{ .Values.cookiesecret | b64enc }}